import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "@/components/footer";
import { SiteNav } from "@/components/site-nav";
import { SITE_DESCRIPTION, SITE_TITLE } from "@/lib/site";

export const metadata: Metadata = {
  metadataBase: new URL("https://sluice-iota.vercel.app"),
  title: { default: SITE_TITLE, template: "%s · sluice" },
  description: SITE_DESCRIPTION,
  icons: {
    // sluice's own glyph (a raised weir gate) is the identity in a tab —
    // BRAND-KIT.md "Icon hierarchy": five identical chip favicons are
    // indistinguishable in a tab strip, which is the one job a favicon has.
    // The chip stays the maker's mark in the footer (Footer.tsx) and the
    // README lockup — association, not identity.
    icon: [
      { url: "/brand/favicon.svg", type: "image/svg+xml" },
      { url: "/brand/favicon-16.png", sizes: "16x16", type: "image/png" },
      { url: "/brand/favicon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/brand/favicon-48.png", sizes: "48x48", type: "image/png" },
    ],
    shortcut: "/brand/favicon.svg",
    apple: [{ url: "/brand/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
    other: [{ rel: "mask-icon", url: "/brand/icon-maskable.svg", color: "#B45309" }],
  },
  openGraph: {
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    url: "https://sluice-iota.vercel.app",
    siteName: "sluice",
    // og.png, not og.svg — social scrapers do not render SVG. Generated by
    // scripts/brand.mjs (`pnpm brand`) straight to the committed asset, so
    // there is exactly one OG-image pipeline, not two.
    images: [{ url: "/brand/og.png", width: 1200, height: 630, alt: "sluice — Agent James" }],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    images: ["/brand/og.png"],
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col bg-paper text-ink antialiased">
        <SiteNav />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
