// SPEC §7 artifact pipeline, stage two: render chaos/RESULTS.md and inject
// the README table between <!-- chaos:begin --> / <!-- chaos:end --> from
// chaos/results/latest.json. Numbers are GENERATED, never hand-written.
//
//   node scripts/chaos-report.mjs           write RESULTS.md + inject README
//   node scripts/chaos-report.mjs --check   fail (exit 1) if the committed
//                                           files differ from what latest.json
//                                           renders — the CI drift gate.
//
// (Behavioural drift — latest.json itself no longer matching a fresh harness
// run — is caught by the eval stage, which re-runs the suite in-process.)
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const LATEST = resolve(ROOT, "chaos", "results", "latest.json");
const RESULTS_MD = resolve(ROOT, "chaos", "RESULTS.md");
const README = resolve(ROOT, "README.md");
const BEGIN = "<!-- chaos:begin -->";
const END = "<!-- chaos:end -->";

/** Deterministic thousands grouping — no locale, no ICU variance. */
const fmt = (n) => String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
const pct = (x) => `${(x * 100).toFixed(1)}%`;

export function renderReadmeBlock(r) {
  const badge = `golden ${r.golden.passed}/${r.golden.total} · fuzz ${r.fuzz.seeds} seeds · ${r.harness.invariantViolations} invariant violations`;
  const lines = [
    `**Chaos harness** — \`${badge}\``,
    "",
    "| metric | naive retry (no sluice) | with sluice |",
    "|---|---|---|",
    `| intent success rate | ${pct(r.baseline.naive.successRate)} | ${pct(r.baseline.sluice.successRate)} (${pct(r.baseline.sluice.failClosedRate)} fail closed — parked \`indeterminate\`, never silent) |`,
    `| duplicate side effects | **${fmt(r.baseline.naive.duplicateEffects)}** | **${fmt(r.baseline.sluice.duplicateEffects)}** |`,
    "",
    `Baseline workload: ${fmt(r.baseline.workload.intents * r.baseline.workload.seeds)} intents delivered ${r.baseline.workload.deliveries[0]}–${r.baseline.workload.deliveries[1]}× each under ${pct(r.baseline.workload.injectedFailureRate)} injected failure (${pct(r.baseline.workload.errorRate)} errors + ${pct(r.baseline.workload.timeoutRate)} landed-but-timed-out).`,
    `Retry amplification under ${pct(r.amplification.injectedFailureRate)} injected failure: **${r.amplification.factor.toFixed(2)}×** downstream attempts per intent (CI gate ≤ ${r.amplification.gate}).`,
    `\`run()\` latency under fault injection: p50 ${fmt(r.latency.p50)} ms · p99 ${fmt(r.latency.p99)} ms — **virtual clock time, not wall clock**.`,
    `Run shape: ${r.harness.scenarios} scenarios × ${r.harness.seedsPerScenario} seeds · ${fmt(r.harness.totalIntents)} intents · ${fmt(r.harness.totalDeliveries)} deliveries · git \`${r.gitSha.slice(0, 7)}\`.`,
    `Regenerate with \`pnpm chaos\` — full tables in [chaos/RESULTS.md](chaos/RESULTS.md).`,
  ];
  return lines.join("\n");
}

export function renderResultsMd(r) {
  const lines = [
    "# Chaos harness results",
    "",
    "Generated by `pnpm chaos` — never edited by hand. CI regenerates and fails on drift",
    "(SPEC §7/§8). All latencies are **virtual clock time, not wall clock**.",
    "",
    `- generated: ${r.generatedAt}`,
    `- git: \`${r.gitSha}\``,
    `- run shape: ${r.harness.scenarios} scenarios × ${r.harness.seedsPerScenario} seeds · ${fmt(r.harness.totalIntents)} logical intents · ${fmt(r.harness.totalDeliveries)} deliveries · ${fmt(r.harness.totalLedger)} committed side effects`,
    `- invariants checked on every run: ${r.harness.invariantsChecked.join(", ")} — **${r.harness.invariantViolations} violations**`,
    `- golden set: **${r.golden.passed}/${r.golden.total}** · fuzz: **${r.fuzz.seeds} seeds, ${r.fuzz.violations} violations**`,
    "",
    "## Baseline: naive retry vs sluice",
    "",
    `Workload: ${fmt(r.baseline.workload.intents)} intents × ${r.baseline.workload.seeds} seeds, each delivered ${r.baseline.workload.deliveries[0]}–${r.baseline.workload.deliveries[1]}×, ${pct(r.baseline.workload.injectedFailureRate)} injected failure (${pct(r.baseline.workload.errorRate)} pre-commit errors + ${pct(r.baseline.workload.timeoutRate)} committed-but-timed-out). The naive client retries every failure up to 3× — including timeouts, which is exactly how an unknown outcome becomes a duplicate charge.`,
    "",
    "| metric | naive retry | with sluice |",
    "|---|---|---|",
    `| intent success rate | ${pct(r.baseline.naive.successRate)} | ${pct(r.baseline.sluice.successRate)} |`,
    `| fail-closed (parked \`indeterminate\`) | — | ${pct(r.baseline.sluice.failClosedRate)} |`,
    `| duplicate side effects | ${fmt(r.baseline.naive.duplicateEffects)} | ${fmt(r.baseline.sluice.duplicateEffects)} |`,
    `| downstream attempts | ${fmt(r.baseline.naive.attempts)} | ${fmt(r.baseline.sluice.attempts)} |`,
    "",
    "sluice trades a few points of reported success for zero duplicates: the unknown-outcome",
    "calls are parked `indeterminate` for a human or an explicit reclaim, never silently",
    "re-fired. The naive column's extra \"successes\" are bought with duplicate side effects.",
    "",
    "## Retry amplification (I6)",
    "",
    `Under ${pct(r.amplification.injectedFailureRate)} injected downstream failure, sluice issued **${r.amplification.factor.toFixed(4)}×** downstream attempts per logical intent (retry budget + full-jitter backoff + breaker). CI gate: ≤ ${r.amplification.gate}.`,
    "",
    "## run() latency under fault injection",
    "",
    `p50 ${fmt(r.latency.p50)} ms · p99 ${fmt(r.latency.p99)} ms over ${fmt(r.latency.samples)} deliveries — **${r.latency.unit}**. The p99 is dominated by scenarios that legitimately wait out lease expiry and slow downstreams; wall-clock runtime of the whole suite is seconds.`,
    "",
    "## Per-scenario rollup",
    "",
    "| scenario | seeds | intents | deliveries | ledger | attempts | duplicates | violations |",
    "|---|---|---|---|---|---|---|---|",
  ];
  for (const s of r.scenarios) {
    lines.push(
      `| ${s.name} | ${s.seeds} | ${fmt(s.intents)} | ${fmt(s.deliveries)} | ${fmt(s.ledger)} | ${fmt(s.attempts)} | ${fmt(s.duplicateEffects)} | ${s.violations} |`
    );
  }
  lines.push(
    "",
    "Ledger < intents in the crash/timeout scenarios is the point: those intents are parked",
    "`indeterminate` (fail closed) instead of executed twice. Duplicates are 0 in every row.",
    ""
  );
  return lines.join("\n");
}

export function injectReadme(readme, block) {
  const begin = readme.indexOf(BEGIN);
  const end = readme.indexOf(END);
  if (begin === -1 || end === -1 || end < begin) {
    throw new Error("README.md is missing the <!-- chaos:begin/end --> markers");
  }
  return `${readme.slice(0, begin + BEGIN.length)}\n${block}\n${readme.slice(end)}`;
}

function main() {
  const check = process.argv.includes("--check");
  const results = JSON.parse(readFileSync(LATEST, "utf8"));
  const block = renderReadmeBlock(results);
  const resultsMd = renderResultsMd(results);
  const readme = readFileSync(README, "utf8");
  const injected = injectReadme(readme, block);

  if (check) {
    let failed = false;
    let committedResults = "";
    try {
      committedResults = readFileSync(RESULTS_MD, "utf8");
    } catch {
      // missing file = drift
    }
    if (committedResults !== resultsMd) {
      console.error("DRIFT: chaos/RESULTS.md does not match chaos/results/latest.json");
      failed = true;
    }
    if (readme !== injected) {
      console.error("DRIFT: the README chaos block does not match chaos/results/latest.json");
      failed = true;
    }
    if (failed) {
      console.error("Run `pnpm chaos` and commit the regenerated artifacts.");
      process.exit(1);
    }
    console.log("chaos-report --check: README block and RESULTS.md match latest.json");
    return;
  }

  writeFileSync(RESULTS_MD, resultsMd);
  writeFileSync(README, injected);
  console.log("chaos-report: wrote chaos/RESULTS.md and injected the README block");
}

main();
