/**
 * identity.json -> apps/web/app/identity.css
 *
 * PORTFOLIO-DESIGN-DNA.md §4: `identity.json` is the ONLY file allowed to vary
 * between the ~28 project sites, and the only thing it contributes to CSS is one
 * line — the project's signal hue. substrate.css (byte-identical everywhere, gate
 * G11) derives --signal / --signal-ink / --signal-glow / --signal-wash from it in
 * both lightings.
 *
 * The generated file is committed so the build has no ordering dependency on this
 * script, but it must never be hand-edited: run `pnpm identity` after changing
 * identity.json. It contains no colour literal of its own (gate G1) — a hue is a
 * number, not a colour.
 *
 * Usage:  node scripts/identity-css.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const identity = JSON.parse(readFileSync(join(ROOT, "identity.json"), "utf8"));

// The six fields the schema allows, checked here rather than trusted — a typo in
// `signal` would silently ship the substrate package's placeholder hue.
const REQUIRED = ["signal", "instrument", "glyph", "lighting", "voice", "chamfer"];
for (const key of REQUIRED) {
  if (!(key in identity)) throw new Error(`identity.json is missing required field: ${key}`);
}
const hue = identity.signal;
if (typeof hue !== "number" || !Number.isFinite(hue) || hue < 0 || hue >= 360) {
  throw new Error(`identity.json signal must be a hue in [0, 360); got ${String(hue)}`);
}
// DNA §3.2: status hues are locked portfolio-wide and must never be relearned per
// project, so a project's signal has to sit at least 25 degrees from all four.
const STATUS = { ok: 152, warn: 75, fail: 27, info: 232 };
for (const [name, h] of Object.entries(STATUS)) {
  const d = Math.abs((((hue - h + 180) % 360) + 360) % 360 - 180);
  if (d < 25) {
    throw new Error(`identity.json signal ${hue} is only ${d.toFixed(1)}deg from --${name} (${h}); needs >= 25`);
  }
}

const out = `/* GENERATED by scripts/identity-css.mjs from identity.json — do not edit.
   PORTFOLIO-DESIGN-DNA.md §4: one line, one hue, the entire per-project colour surface.
   Everything else comes from public/substrate/substrate.css, byte-identical (gate G11). */
:root {
  --signal-h: ${hue};
}
`;
writeFileSync(join(ROOT, "apps/web/app/identity.css"), out);
process.stdout.write(`identity.css written: --signal-h: ${hue} (lighting ${identity.lighting}, chamfer ${identity.chamfer})\n`);
